# Generated by Django 3.2.5 on 2021-08-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicplayer_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/'),
        ),
        migrations.AddField(
            model_name='music',
            name='quality',
            field=models.IntegerField(default=1),
        ),
    ]
