# Generated by Django 3.2.5 on 2021-08-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicplayer_app', '0002_auto_20210807_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='trackes/'),
        ),
    ]
